export const NetworkGeographys: any = [
  {
    id: 1,
    username: "Britteny Fluger",
    area: "rural",
    region: "eastern",
    state: "johor",
    district: "ayer keroh",
    majlis: "MPAK",
    latitude: "40.96778",
    longitude: "19.82111"
  },
  {
    id: 2,
    username: "Wynnie Dinan",
    area: "city",
    region: "eastern",
    state: "kedah",
    district: "kota bharu",
    majlis: "MPAS",
    latitude: 15.5450531,
    longitude: 121.0872097
  },
  {
    id: 3,
    username: "Arlette Portlock",
    area: "city",
    region: "western",
    state: "negeri sembilan",
    district: "alor setar",
    majlis: "MPAK",
    latitude: -33.745727,
    longitude: -61.961036
  },
  {
    id: 4,
    username: "Karim Duce",
    area: "rural",
    region: "northern",
    state: "negeri sembilan",
    district: "alor setar",
    majlis: "MPAK",
    latitude: 30.378326,
    longitude: 111.450006
  },
  {
    id: 5,
    username: "Marcelline Rideout",
    area: "city",
    region: "northern",
    state: "johor",
    district: "ayer keroh",
    majlis: "MPAS",
    latitude: 52.4981613,
    longitude: 13.5581889
  },
  {
    id: 6,
    username: "Dulce Teresia",
    area: "village",
    region: "western",
    state: "melaka",
    district: "ayer keroh",
    majlis: "MPAS",
    latitude: 44.9690446,
    longitude: 15.9431582
  },
  {
    id: 7,
    username: "Rutger Capon",
    area: "village",
    region: "eastern",
    state: "johor",
    district: "ayer keroh",
    majlis: "MPS",
    latitude: 47.5173564,
    longitude: 42.1602043
  },
  {
    id: 8,
    username: "Lyle Purdy",
    area: "village",
    region: "western",
    state: "kelantan",
    district: "seremban",
    majlis: "MPKB",
    latitude: 59.9344779,
    longitude: 30.3842343
  },
  {
    id: 9,
    username: "Bryant Hammill",
    area: "village",
    region: "western",
    state: "negeri sembilan",
    district: "seremban",
    majlis: "MPAK",
    latitude: 47.510162,
    longitude: 19.0238539
  },
  {
    id: 10,
    username: "Renault Giorgielli",
    area: "village",
    region: "eastern",
    state: "johor",
    district: "kota bharu",
    majlis: "MPKB",
    latitude: 31.092719,
    longitude: 93.812858
  },
  {
    id: 11,
    username: "Charlena Giaomozzo",
    area: "city",
    region: "eastern",
    state: "kelantan",
    district: "alor setar",
    majlis: "MPAK",
    latitude: -8.7688975,
    longitude: 116.3957965
  },
  {
    id: 12,
    username: "Ynez Crum",
    area: "village",
    region: "northern",
    state: "kelantan",
    district: "kota bharu",
    majlis: "MPAS",
    latitude: -7.45,
    longitude: 108.033333
  },
  {
    id: 13,
    username: "Ronny Bentley",
    area: "rural",
    region: "eastern",
    state: "negeri sembilan",
    district: "ayer keroh",
    majlis: "MPAS",
    latitude: 48.4089744,
    longitude: 135.123385
  },
  {
    id: 14,
    username: "Kassey Freda",
    area: "rural",
    region: "southern",
    state: "kedah",
    district: "alor setar",
    majlis: "MPAK",
    latitude: -6.6551319,
    longitude: 105.8466437
  },
  {
    id: 15,
    username: "Annabela Campagne",
    area: "rural",
    region: "eastern",
    state: "kedah",
    district: "ayer keroh",
    majlis: "MPS",
    latitude: 30.543283,
    longitude: 117.062623
  },
  {
    id: 16,
    username: "Nevil Tearney",
    area: "rural",
    region: "western",
    state: "negeri sembilan",
    district: "segamat",
    majlis: "MPKB",
    latitude: 31.364042,
    longitude: 108.520914
  },
  {
    id: 17,
    username: "Hyacinthie Harston",
    area: "rural",
    region: "eastern",
    state: "kelantan",
    district: "seremban",
    majlis: "MPS",
    latitude: 36.4406171,
    longitude: 119.2131226
  },
  {
    id: 18,
    username: "Paco Rawle",
    area: "city",
    region: "western",
    state: "melaka",
    district: "segamat",
    majlis: "MPS",
    latitude: 48.9175083,
    longitude: 2.3514328
  },
  {
    id: 19,
    username: "Siobhan Matthensen",
    area: "village",
    region: "eastern",
    state: "kedah",
    district: "alor setar",
    majlis: "MPKB",
    latitude: 52.138523,
    longitude: 16.8924785
  },
  {
    id: 20,
    username: "Redford Salomon",
    area: "rural",
    region: "southern",
    state: "kelantan",
    district: "seremban",
    majlis: "MPS",
    latitude: -6.9244162,
    longitude: 112.4142453
  },
  {
    id: 21,
    username: "Marlow Kenrack",
    area: "city",
    region: "western",
    state: "kelantan",
    district: "alor setar",
    majlis: "MPAK",
    latitude: "55.59754",
    longitude: "38.47134"
  },
  {
    id: 22,
    username: "Hank Dinesen",
    area: "city",
    region: "eastern",
    state: "kelantan",
    district: "seremban",
    majlis: "MPS",
    latitude: 40.5045999,
    longitude: -7.9318645
  },
  {
    id: 23,
    username: "Carie Beauchop",
    area: "city",
    region: "eastern",
    state: "johor",
    district: "kota bharu",
    majlis: "MPAS",
    latitude: 14.5661645,
    longitude: 121.0321655
  },
  {
    id: 24,
    username: "Bret Waterstone",
    area: "rural",
    region: "southern",
    state: "melaka",
    district: "kota bharu",
    majlis: "MPS",
    latitude: 48.5847594,
    longitude: -68.1942711
  },
  {
    id: 25,
    username: "Evan Huegett",
    area: "rural",
    region: "northern",
    state: "kelantan",
    district: "seremban",
    majlis: "MPAK",
    latitude: 27.522725,
    longitude: 112.507849
  },
  {
    id: 26,
    username: "Nerta Spavins",
    area: "rural",
    region: "eastern",
    state: "melaka",
    district: "alor setar",
    majlis: "MPS",
    latitude: -6.2690475,
    longitude: 106.3287199
  },
  {
    id: 27,
    username: "Vonni Gascone",
    area: "village",
    region: "eastern",
    state: "kelantan",
    district: "alor setar",
    majlis: "MPS",
    latitude: 46.9063815,
    longitude: 102.7636515
  },
  {
    id: 28,
    username: "Sherye Oke",
    area: "rural",
    region: "southern",
    state: "melaka",
    district: "seremban",
    majlis: "MPS",
    latitude: 47.8143666,
    longitude: 38.9149216
  },
  {
    id: 29,
    username: "Filberto Hawksley",
    area: "city",
    region: "northern",
    state: "melaka",
    district: "alor setar",
    majlis: "MPS",
    latitude: 54.2877219,
    longitude: 17.6311856
  },
  {
    id: 30,
    username: "Tann Bonney",
    area: "city",
    region: "southern",
    state: "johor",
    district: "kota bharu",
    majlis: "MPS",
    latitude: 26.076336,
    longitude: 103.556409
  },
  {
    id: 31,
    username: "Ted Bickardike",
    area: "city",
    region: "eastern",
    state: "kedah",
    district: "kota bharu",
    majlis: "MPAK",
    latitude: 41.8905758,
    longitude: 140.6934778
  },
  {
    id: 32,
    username: "Cornall Schneider",
    area: "city",
    region: "western",
    state: "melaka",
    district: "alor setar",
    majlis: "MPS",
    latitude: 51.1490898,
    longitude: 108.9418923
  },
  {
    id: 33,
    username: "Tannie Negro",
    area: "city",
    region: "northern",
    state: "melaka",
    district: "segamat",
    majlis: "MPS",
    latitude: 12.4082969,
    longitude: 9.5291085
  },
  {
    id: 34,
    username: "Mitchael Royan",
    area: "rural",
    region: "eastern",
    state: "melaka",
    district: "segamat",
    majlis: "MPS",
    latitude: 41.376241,
    longitude: 19.7881955
  },
  {
    id: 35,
    username: "Tiffy Drummond",
    area: "rural",
    region: "southern",
    state: "negeri sembilan",
    district: "alor setar",
    majlis: "MPAS",
    latitude: 43.2587403,
    longitude: 17.8880075
  },
  {
    id: 36,
    username: "Vivie Wass",
    area: "city",
    region: "eastern",
    state: "kedah",
    district: "alor setar",
    majlis: "MPS",
    latitude: 55.499775,
    longitude: 25.635173
  },
  {
    id: 37,
    username: "Blondell Bloxam",
    area: "city",
    region: "western",
    state: "melaka",
    district: "alor setar",
    majlis: "MPS",
    latitude: -8.727807,
    longitude: 115.5444231
  },
  {
    id: 38,
    username: "Terrel Fass",
    area: "village",
    region: "eastern",
    state: "negeri sembilan",
    district: "ayer keroh",
    majlis: "MPAK",
    latitude: -5.3810959,
    longitude: 105.2955575
  },
  {
    id: 39,
    username: "Heath Winnett",
    area: "city",
    region: "eastern",
    state: "kelantan",
    district: "alor setar",
    majlis: "MPS",
    latitude: 59.3015113,
    longitude: 17.9981495
  },
  {
    id: 40,
    username: "Ronna Cowin",
    area: "rural",
    region: "southern",
    state: "kelantan",
    district: "alor setar",
    majlis: "MPAS",
    latitude: 36.1473783,
    longitude: 136.1682227
  },
  {
    id: 41,
    username: "Aretha Nanni",
    area: "rural",
    region: "eastern",
    state: "kedah",
    district: "seremban",
    majlis: "MPAK",
    latitude: -24.314422,
    longitude: -46.9936142
  },
  {
    id: 42,
    username: "Chryste Sonschein",
    area: "rural",
    region: "northern",
    state: "johor",
    district: "ayer keroh",
    majlis: "MPAK",
    latitude: 56.2094069,
    longitude: 14.8470274
  },
  {
    id: 43,
    username: "Dina Seeney",
    area: "city",
    region: "eastern",
    state: "negeri sembilan",
    district: "seremban",
    majlis: "MPS",
    latitude: 14.273035,
    longitude: 122.564262
  },
  {
    id: 44,
    username: "Stormi Worley",
    area: "rural",
    region: "eastern",
    state: "kedah",
    district: "alor setar",
    majlis: "MPS",
    latitude: 22.481274,
    longitude: 113.217762
  },
  {
    id: 45,
    username: "Clerissa Walsh",
    area: "city",
    region: "southern",
    state: "melaka",
    district: "seremban",
    majlis: "MPAK",
    latitude: 5.23113,
    longitude: 96.7524103
  },
  {
    id: 46,
    username: "Georgiana Ramos",
    area: "village",
    region: "eastern",
    state: "johor",
    district: "ayer keroh",
    majlis: "MPAS",
    latitude: "-7.1724",
    longitude: "111.501"
  },
  {
    id: 47,
    username: "Ede Linstead",
    area: "village",
    region: "eastern",
    state: "kelantan",
    district: "kota bharu",
    majlis: "MPS",
    latitude: 39.9167763,
    longitude: -7.4517472
  },
  {
    id: 48,
    username: "Emilie Axtell",
    area: "rural",
    region: "southern",
    state: "melaka",
    district: "ayer keroh",
    majlis: "MPKB",
    latitude: 32.045589,
    longitude: 34.876578
  },
  {
    id: 49,
    username: "Tore Stainer",
    area: "city",
    region: "southern",
    state: "melaka",
    district: "kota bharu",
    majlis: "MPKB",
    latitude: 23.624141,
    longitude: 116.289146
  },
  {
    id: 50,
    username: "Nico Deave",
    area: "rural",
    region: "northern",
    state: "kedah",
    district: "alor setar",
    majlis: "MPS",
    latitude: 63.8294111,
    longitude: 15.3600636
  }
];
