export const UserAccesses: any = [
  {
    id: 1,
    username: "Emmalyn Jacmar",
    email: "ejacmar0@dropbox.com",
    role: "branch",
    module: "acceptance and approval",
    action: "read",
    data: "mobile",
    rule: "analysis",
    password: "mnrJxEvT",
    dateactivity: "2019-08-06",
    timeactivity: "12:17 AM"
  },
  {
    id: 2,
    username: "Constanta Muriel",
    email: "cmuriel1@forbes.com",
    role: "department",
    module: "acceptance and approval",
    action: "create",
    data: "mobile",
    rule: "analysis",
    password: "Qpr66JaJgG1",
    dateactivity: "2019-08-19",
    timeactivity: "10:26 AM"
  },
  {
    id: 3,
    username: "Martie Hortop",
    email: "mhortop2@oaic.gov.au",
    role: "department",
    module: "network geography",
    action: "create",
    data: "network",
    rule: "monitoring",
    password: "AaYqspKBTe",
    dateactivity: "2019-07-06",
    timeactivity: "10:23 AM"
  },
  {
    id: 4,
    username: "Melli Schaffler",
    email: "mschaffler3@cnet.com",
    role: "department",
    module: "network geography",
    action: "read",
    data: "network",
    rule: "analysis",
    password: "jkr63SzTKU",
    dateactivity: "2019-03-25",
    timeactivity: "3:11 PM"
  },
  {
    id: 5,
    username: "Aloin Stickney",
    email: "astickney4@psu.edu",
    role: "admin",
    module: "delivery and rollout",
    action: "delete",
    data: "stock",
    rule: "crud",
    password: "RjFILOx6VA",
    dateactivity: "2019-12-23",
    timeactivity: "3:02 PM"
  },
  {
    id: 6,
    username: "Janot Temprell",
    email: "jtemprell5@nbcnews.com",
    role: "headquarters",
    module: "user access",
    action: "read",
    data: "mobile",
    rule: "analysis",
    password: "B7zXJBKWa",
    dateactivity: "2019-11-23",
    timeactivity: "5:57 PM"
  },
  {
    id: 7,
    username: "Maurizia Ffrench",
    email: "mffrench6@sitemeter.com",
    role: "headquarters",
    module: "asset management",
    action: "delete",
    data: "network",
    rule: "reporting",
    password: "KYeFRoFnNsi",
    dateactivity: "2019-12-21",
    timeactivity: "2:11 AM"
  },
  {
    id: 8,
    username: "Georgeanne Ferrie",
    email: "gferrie7@paginegialle.it",
    role: "department",
    module: "delivery and rollout",
    action: "update",
    data: "network",
    rule: "crud",
    password: "QiM2R3C8",
    dateactivity: "2019-04-09",
    timeactivity: "7:55 AM"
  },
  {
    id: 9,
    username: "Jeffy Meakes",
    email: "jmeakes8@ezinearticles.com",
    role: "admin",
    module: "acceptance and approval",
    action: "delete",
    data: "network",
    rule: "reporting",
    password: "4xCNwWZ",
    dateactivity: "2019-06-20",
    timeactivity: "1:09 PM"
  },
  {
    id: 10,
    username: "Meryl Tod",
    email: "mtod9@surveymonkey.com",
    role: "department",
    module: "network geography",
    action: "read",
    data: "network",
    rule: "crud",
    password: "NXAHMj",
    dateactivity: "2019-08-27",
    timeactivity: "4:05 PM"
  },
  {
    id: 11,
    username: "Austen Cloney",
    email: "acloneya@diigo.com",
    role: "branch",
    module: "delivery and rollout",
    action: "delete",
    data: "mobile",
    rule: "reporting",
    password: "XLxMD1",
    dateactivity: "2019-11-15",
    timeactivity: "5:43 AM"
  },
  {
    id: 12,
    username: "Normand Lillico",
    email: "nlillicob@discovery.com",
    role: "branch",
    module: "network geography",
    action: "delete",
    data: "network",
    rule: "collecting",
    password: "8MMk4NoPVxGf",
    dateactivity: "2019-05-08",
    timeactivity: "3:02 PM"
  },
  {
    id: 13,
    username: "Ryon Kuhnwald",
    email: "rkuhnwaldc@reverbnation.com",
    role: "department",
    module: "user access",
    action: "delete",
    data: "mobile",
    rule: "crud",
    password: "2116gb",
    dateactivity: "2020-02-12",
    timeactivity: "11:54 PM"
  },
  {
    id: 14,
    username: "Waite O'Carroll",
    email: "wocarrolld@dailymail.co.uk",
    role: "branch",
    module: "network geography",
    action: "update",
    data: "equipment",
    rule: "analysis",
    password: "GSrZtmFLyR",
    dateactivity: "2019-05-20",
    timeactivity: "8:43 PM"
  },
  {
    id: 15,
    username: "Fayth Amori",
    email: "famorie@unblog.fr",
    role: "department",
    module: "delivery and rollout",
    action: "create",
    data: "mobile",
    rule: "reporting",
    password: "yLn20ovm4nMG",
    dateactivity: "2019-06-18",
    timeactivity: "6:43 AM"
  },
  {
    id: 16,
    username: "Augusta Byrd",
    email: "abyrdf@cbc.ca",
    role: "headquarters",
    module: "user access",
    action: "delete",
    data: "equipment",
    rule: "reporting",
    password: "BcvihO4tm",
    dateactivity: "2020-01-11",
    timeactivity: "10:37 PM"
  },
  {
    id: 17,
    username: "Delmor Bird",
    email: "dbirdg@mashable.com",
    role: "user",
    module: "user access",
    action: "delete",
    data: "stock",
    rule: "monitoring",
    password: "zoZkTbNsc5Q",
    dateactivity: "2020-01-08",
    timeactivity: "9:18 AM"
  },
  {
    id: 18,
    username: "Teresita Ablott",
    email: "tablotth@w3.org",
    role: "branch",
    module: "network geography",
    action: "read",
    data: "mobile",
    rule: "analysis",
    password: "mK7OugW",
    dateactivity: "2019-05-12",
    timeactivity: "7:00 AM"
  },
  {
    id: 19,
    username: "Cchaddie Puddin",
    email: "cpuddini@miibeian.gov.cn",
    role: "admin",
    module: "asset management",
    action: "create",
    data: "equipment",
    rule: "crud",
    password: "JVocE0a",
    dateactivity: "2020-02-04",
    timeactivity: "8:38 AM"
  },
  {
    id: 20,
    username: "Gilda Di Maggio",
    email: "gdij@illinois.edu",
    role: "department",
    module: "acceptance and approval",
    action: "read",
    data: "stock",
    rule: "crud",
    password: "mSdPmT",
    dateactivity: "2019-12-21",
    timeactivity: "8:56 PM"
  },
  {
    id: 21,
    username: "Pacorro Devonside",
    email: "pdevonsidek@desdev.cn",
    role: "department",
    module: "acceptance and approval",
    action: "update",
    data: "cloud",
    rule: "analysis",
    password: "Bbsr5aMq",
    dateactivity: "2019-06-21",
    timeactivity: "12:22 AM"
  },
  {
    id: 22,
    username: "Windham Crosetto",
    email: "wcrosettol@msn.com",
    role: "admin",
    module: "asset management",
    action: "update",
    data: "mobile",
    rule: "collecting",
    password: "Mo5Itu3YAvdH",
    dateactivity: "2019-08-15",
    timeactivity: "9:38 PM"
  },
  {
    id: 23,
    username: "Yehudi Deek",
    email: "ydeekm@mysql.com",
    role: "department",
    module: "delivery and rollout",
    action: "delete",
    data: "stock",
    rule: "crud",
    password: "b9SMbk",
    dateactivity: "2019-03-18",
    timeactivity: "5:19 AM"
  },
  {
    id: 24,
    username: "Jobina Alexandrou",
    email: "jalexandroun@cbslocal.com",
    role: "headquarters",
    module: "delivery and rollout",
    action: "update",
    data: "stock",
    rule: "monitoring",
    password: "j4Ns5jk",
    dateactivity: "2019-11-19",
    timeactivity: "7:11 PM"
  },
  {
    id: 25,
    username: "Sherri Towers",
    email: "stowerso@nsw.gov.au",
    role: "headquarters",
    module: "planning",
    action: "delete",
    data: "stock",
    rule: "collecting",
    password: "xTY4Iv",
    dateactivity: "2019-08-15",
    timeactivity: "5:45 AM"
  },
  {
    id: 26,
    username: "Terrijo Giordano",
    email: "tgiordanop@senate.gov",
    role: "user",
    module: "delivery and rollout",
    action: "update",
    data: "stock",
    rule: "crud",
    password: "GSMxYa9",
    dateactivity: "2019-07-31",
    timeactivity: "7:07 PM"
  },
  {
    id: 27,
    username: "Ike Bearns",
    email: "ibearnsq@techcrunch.com",
    role: "user",
    module: "planning",
    action: "delete",
    data: "equipment",
    rule: "monitoring",
    password: "GLp8tmb",
    dateactivity: "2020-01-01",
    timeactivity: "1:20 AM"
  },
  {
    id: 28,
    username: "Gerrie O' Mahony",
    email: "gor@liveinternet.ru",
    role: "headquarters",
    module: "network geography",
    action: "update",
    data: "mobile",
    rule: "monitoring",
    password: "ZurI74sLr",
    dateactivity: "2019-04-05",
    timeactivity: "11:07 PM"
  },
  {
    id: 29,
    username: "Miguelita Greaser",
    email: "mgreasers@yandex.ru",
    role: "branch",
    module: "delivery and rollout",
    action: "read",
    data: "stock",
    rule: "monitoring",
    password: "0wiObGZk",
    dateactivity: "2020-02-27",
    timeactivity: "3:36 AM"
  },
  {
    id: 30,
    username: "Joaquin Mallock",
    email: "jmallockt@icio.us",
    role: "admin",
    module: "acceptance and approval",
    action: "read",
    data: "equipment",
    rule: "analysis",
    password: "okGYhLQZzVzX",
    dateactivity: "2020-01-10",
    timeactivity: "9:16 PM"
  },
  {
    id: 31,
    username: "Angelia Leroy",
    email: "aleroyu@mit.edu",
    role: "department",
    module: "acceptance and approval",
    action: "read",
    data: "stock",
    rule: "analysis",
    password: "cZQF3lPDkG",
    dateactivity: "2019-03-08",
    timeactivity: "10:25 AM"
  },
  {
    id: 32,
    username: "Jacquie McCarver",
    email: "jmccarverv@opera.com",
    role: "department",
    module: "asset management",
    action: "create",
    data: "equipment",
    rule: "analysis",
    password: "2Q8JJrGHbo",
    dateactivity: "2019-12-31",
    timeactivity: "12:44 PM"
  },
  {
    id: 33,
    username: "Ava Birks",
    email: "abirksw@studiopress.com",
    role: "admin",
    module: "asset management",
    action: "create",
    data: "mobile",
    rule: "crud",
    password: "6yQhrvjs",
    dateactivity: "2019-08-04",
    timeactivity: "3:48 PM"
  },
  {
    id: 34,
    username: "Adam Bickersteth",
    email: "abickerstethx@theatlantic.com",
    role: "admin",
    module: "planning",
    action: "read",
    data: "cloud",
    rule: "reporting",
    password: "zzjvlu",
    dateactivity: "2019-11-12",
    timeactivity: "3:47 PM"
  },
  {
    id: 35,
    username: "Bob Greder",
    email: "bgredery@imgur.com",
    role: "user",
    module: "user access",
    action: "delete",
    data: "cloud",
    rule: "monitoring",
    password: "13XN2PCP0J7O",
    dateactivity: "2019-07-31",
    timeactivity: "12:07 PM"
  },
  {
    id: 36,
    username: "Madelaine Joannidi",
    email: "mjoannidiz@loc.gov",
    role: "branch",
    module: "network geography",
    action: "delete",
    data: "stock",
    rule: "collecting",
    password: "ywtQqL",
    dateactivity: "2019-08-22",
    timeactivity: "10:19 PM"
  },
  {
    id: 37,
    username: "Fidel MacGiolla Pheadair",
    email: "fmacgiolla10@ebay.com",
    role: "headquarters",
    module: "network geography",
    action: "delete",
    data: "cloud",
    rule: "collecting",
    password: "1ZIgFD",
    dateactivity: "2019-05-06",
    timeactivity: "9:48 AM"
  },
  {
    id: 38,
    username: "Clotilda Esby",
    email: "cesby11@taobao.com",
    role: "user",
    module: "delivery and rollout",
    action: "create",
    data: "mobile",
    rule: "collecting",
    password: "HWltcv2wLoWs",
    dateactivity: "2019-09-25",
    timeactivity: "9:22 AM"
  },
  {
    id: 39,
    username: "Siana Desbrow",
    email: "sdesbrow12@technorati.com",
    role: "branch",
    module: "network geography",
    action: "update",
    data: "mobile",
    rule: "collecting",
    password: "Og4jB7Nf",
    dateactivity: "2020-02-21",
    timeactivity: "1:00 AM"
  },
  {
    id: 40,
    username: "Berk Killerby",
    email: "bkillerby13@ed.gov",
    role: "user",
    module: "asset management",
    action: "read",
    data: "mobile",
    rule: "monitoring",
    password: "SutnIA",
    dateactivity: "2020-02-07",
    timeactivity: "2:36 AM"
  },
  {
    id: 41,
    username: "Misha Tombling",
    email: "mtombling14@fastcompany.com",
    role: "branch",
    module: "acceptance and approval",
    action: "create",
    data: "network",
    rule: "reporting",
    password: "jvG4Ei",
    dateactivity: "2019-07-09",
    timeactivity: "3:54 AM"
  },
  {
    id: 42,
    username: "Romona Grimes",
    email: "rgrimes15@soundcloud.com",
    role: "branch",
    module: "delivery and rollout",
    action: "delete",
    data: "equipment",
    rule: "collecting",
    password: "DR72578V",
    dateactivity: "2019-07-12",
    timeactivity: "2:52 AM"
  },
  {
    id: 43,
    username: "Peterus Altofts",
    email: "paltofts16@washingtonpost.com",
    role: "user",
    module: "asset management",
    action: "read",
    data: "mobile",
    rule: "monitoring",
    password: "Wfs8CeqniAHJ",
    dateactivity: "2019-11-18",
    timeactivity: "6:42 PM"
  },
  {
    id: 44,
    username: "Arte McCardle",
    email: "amccardle17@tinypic.com",
    role: "headquarters",
    module: "planning",
    action: "create",
    data: "mobile",
    rule: "collecting",
    password: "bYRrYegULeO",
    dateactivity: "2019-05-20",
    timeactivity: "3:39 PM"
  },
  {
    id: 45,
    username: "Marcela Bennitt",
    email: "mbennitt18@geocities.jp",
    role: "admin",
    module: "user access",
    action: "read",
    data: "stock",
    rule: "reporting",
    password: "Z23yZPQSDPa",
    dateactivity: "2020-01-15",
    timeactivity: "5:31 PM"
  },
  {
    id: 46,
    username: "Lewie Balhatchet",
    email: "lbalhatchet19@umich.edu",
    role: "department",
    module: "acceptance and approval",
    action: "read",
    data: "network",
    rule: "collecting",
    password: "V9FSSXC",
    dateactivity: "2019-09-14",
    timeactivity: "4:44 AM"
  },
  {
    id: 47,
    username: "Marlane Le Houx",
    email: "mle1a@desdev.cn",
    role: "admin",
    module: "asset management",
    action: "read",
    data: "network",
    rule: "crud",
    password: "ZEgDssVD37uW",
    dateactivity: "2019-03-16",
    timeactivity: "9:32 PM"
  },
  {
    id: 48,
    username: "Trixy Baddiley",
    email: "tbaddiley1b@google.com.au",
    role: "admin",
    module: "user access",
    action: "update",
    data: "cloud",
    rule: "monitoring",
    password: "FIuyh9ex",
    dateactivity: "2019-03-23",
    timeactivity: "3:24 AM"
  },
  {
    id: 49,
    username: "Corena Georgeot",
    email: "cgeorgeot1c@1und1.de",
    role: "user",
    module: "user access",
    action: "create",
    data: "cloud",
    rule: "analysis",
    password: "pFz7Kcjt8O",
    dateactivity: "2019-04-14",
    timeactivity: "9:12 PM"
  },
  {
    id: 50,
    username: "Meagan Zealy",
    email: "mzealy1d@mit.edu",
    role: "headquarters",
    module: "planning",
    action: "read",
    data: "cloud",
    rule: "crud",
    password: "Q7WPHjkAZVD0",
    dateactivity: "2019-09-24",
    timeactivity: "7:03 AM"
  }
];
